### ISSUE TITLE
Create registration layer on server.

### ISSUE THREAD

**Issue by anpilogoff-developer** [anpilogoff-developer/THEproject#11]
-Настройка контекста ресурсов в файле конфигурации context.xml(Tomcat)
-Реализовать доступ сервлета к БД согласно паттерну DAO, где уровень сервиса использует слой доступа к данным;
     ** UserService - описывающий/реализующий безнеслогику
     ** UserDAO -  Слой доступа к Данным(Data Access Layer) содержащий в себе способы подключения и взаимодейтвия с БД.
-Создать сервлет регистрации("SignUpServlet"):
     ** Добавить  datasource как зависимость при инициализации сервлета.

**Comment by anpilogoff-developer** [comment]
@anpilogov-backend  как успехи? Что-то Вас давно не слышно... Есть какие-то затрудняющие нюансы?

**Comment by anpilogov-backend** [comment]
@anpilogoff-developer  Hello. Нюанс с пониманием многопоточности... В работе!
