### ISSUE TITLE
Add signUp confirmation by e-mail.

### ISSUE THREAD

**Issue by anpilogoff-developer** [anpilogoff-developer/THEproject#12]
### Цель:
Продумать и реализовать  серверный функционал для отправки e-mail. 

### Задачи:
- [x] - Установить и настроить "Postfix" исключительно на отправку. 
- [x] - Создать сервис "EmailService".
- [x] - Добавить метод confirm() в слой сервиса и DAO. 
- [x] - Тесты -> соответственною.

1. Из запроса извлекаются параметры логин и пароль.

2. Проверяется наличие записи с таким логином в базе данных. Если запись не найдена, создается новый пользователь с заполнением его данных из запроса. Значение поля '**confirmed**' устанавливается в "**false**"
3. На основе логина и пароля генерируется **ТОКЕН** 
4. Создается запись в таблице "**confirmation_tokens**" с сгенерированным токеном и id нового неподтверждённого пользовател

5. Формируется, затем отправляется письмо, содержащее ссылку "**https://anpilogoff-dev.ru/signUp?confirm_token=<сгенеренный_токен>**;  получателем письма указывается электронная почта нового неподтверждённого пользователя.

6. При переходе по ссылке из письма происходит обращение к сервлету "SignUp", на основе полученного из запроса токена происходит поиск записи в таблице "confirmation_tokens" , извлекается 'id' и эта  запись удаляется. Затем, используя полученный 'id' находится пользователь в таблице "users", и его поле 'confirmed' изменяется на "true".

**Comment by anpilogoff-developer** [comment]
@anpilogov-backend , как успехи?)

**Comment by anpilogov-backend** [comment]
> @anpilogov-backend , как успехи?)

Установил "Postfix" на VPS, после множества попыток  закомментил пару строк в конфигах  и всё отлично заработало...закомичу в течении дня...

**Comment by anpilogov-backend** [comment]
йо. проверка связи.. @anpilogov-backend

**Comment by anpilogoff-developer** [comment]
как поживает email-confirmation?

**Comment by anpilogov-backend** [comment]
**!!!ВАЖНО!!!**

В базе данных был настроен триггер, который автоматически устанавливает значение поля "confirmed" в таблице "users" в "true" при удалении записи из таблицы "users_confirm_codes". Поле "user_login" в таблице "users_confirm_codes" действует как внешний ключ, ссылающийся на поле "login" в таблице "users".

**Comment by anpilogov-backend** [comment]
> как поживает email-confirmation?

Живее всех живых)) Протестчен и готов к работе. Осталась документация  -   PR coming soon.. ; )
